services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: |
      pipx install virtualenv
      python3 -m virtualenv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python app.py
    autoDeploy: true
