services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install --upgrade pip"
    startCommand: "python3 -m pip install flask openai requests --no-cache-dir; python3 app.py"
    autoDeploy: true
