services:
  - type: web
    name: yurika-tts
    env: python
    plan: free
    region: singapore
    buildCommand: |
      apt-get update
      # OpenJTalk と必要な辞書をインストール
      apt-get install -y open-jtalk mecab-ipadic-utf8 curl unzip
      # Mei音声モデルを確実に配置
      mkdir -p /usr/share/hts-voice/mei
      curl -L -o /tmp/mei_voice.zip "https://sourceforge.net/projects/mmdagent/files/MMDAgent_Example/MMDAgent_Example-1.7/MMDAgent_Example-1.7.zip/download"
      unzip -o /tmp/mei_voice.zip -d /tmp/mei
      cp /tmp/mei/MMDAgent_Example-1.7/Voice/mei/*.htsvoice /usr/share/hts-voice/mei/
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 1 --bind 0.0.0.0:$PORT
