services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: "python3 -m pip install -r requirements.txt"
    startCommand: "python3 bunsekiyou.py"
    autoDeploy: true
