services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: |
      python3 -m pip install --upgrade pip
      python3 -m pip install --break-system-packages -r requirements.txt
    startCommand: python3 app.py
    autoDeploy: true
