services:
  - type: web
    name: yurika-tts
    env: python
    plan: free
    region: singapore
    buildCommand: |
      apt-get update && apt-get install -y open-jtalk hts-voice-mei mecab-ipadic-utf8
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 1 --bind 0.0.0.0:$PORT
