services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python dynamic_core.py"
    autoDeploy: true
