services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: |
      pip install --upgrade pip
    startCommand: |
      pip install --no-cache-dir -r requirements.txt
      python3 app.py
    autoDeploy: true
