services:
  - type: web
    name: zisakuDAPyakasutamuGPTtukutta13666
    env: python
    plan: free
    region: singapore
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
